language: python

python:
  - "3.7"
  - "3.8"

env:
  - NUMPY_VERSION=1.18
  - NUMPY_VERSION=1.17
  - NUMPY_VERSION=1.16

before_install:
  - pip install numpy==$NUMPY_VERSION
  - pip install healpy

install:
  - python setup.py develop

before_script:
  - pip install pytest
  - pip install pytest-cov

script:
  - pytest -v tests/ --cov=cmbpix/